//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFinanceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public System.Guid Id { get; set; }
        public string Symbol { get; set; }
        public int Shares { get; set; }
        public System.Guid EntryId { get; set; }
    }
}
